[package]
name = "avr_periphery"
version = "0.1.0"
authors = ["Niklas Kuehl <nkuehl39@gmx.de>"]

[dependencies]
arduino = { path = "../ruduino", version = "0.1" }
avrlib = { path = "../avrlib", version = "0.1" }